apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice-prod
  template:
    metadata:
      labels:
        app: productcatalogservice-prod
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.3
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 800m
            memory: 512Mi
