kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ro-prom-bind
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ro-prom
  apiGroup: rbac.authorization.k8s.io
