apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentsrv
  labels:
    app: paymentsrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentsrv
  template:
    metadata:
      labels:
        app: paymentsrv
    spec:
      containers:
      - name: paymentsrv
        image: ttl.sh/otus-demo-paymentsrv:5h
        env:
        - name : PORT
          value: "9000"
        - name: DISABLE_PROFILER
          value: "1"
