apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: paymentservice
  template:
    metadata:
      labels:
        tier: paymentservice
    spec:
      containers:
      - name: paymentsrv
        image: ttl.sh/otus-demo-paymentsrv:5h
        env:
        - name : PORT
          value: "9000"
        - name: DISABLE_PROFILER
          value: "1"
