apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
     namespace: default
     name: iclaim
  iscsi:
     targetPortal: 192.168.49.1
     iqn: iqn.2003-01.org.linux-iscsi.server.x8664:sn.334bcc4c2312
     lun: 0
     fsType: 'ext4'
     readOnly: fals
